#!/bin/sh

function send_notification() {
        light=$(light -G)
        dunstify -a "changelight" -u low -r "9993" -h int:value:"$light" -i "light-$1" "Brightness: ${light}%" -t 2000
}


case $1 in 
	-S)
		light -S $2
		send_notification $1
		;;
	-U)
		light -U $2
		send_notification $1
		;;
	-A)
		light -A $2
		send_notification $1
		;;
esac
