#!/bin/sh

alart() {
    notify-send -h string:bgcolor:\#63241a "󰀠 Done GET UP!!" "$* ended"
    mpv --loop=5 ~/.local/assets/bell.m4a
}

if [ "$1" = "u" ]
then
    countdown -up $(date -d @$(($(date '+%s') + 2400)) '+%H:%M')
    exit
fi

countdown $1  && alart "$* timmer"
[ "$2" = "s" ] && exit 0

sec=2400
countdown -up $(date -d @$(($(date '+%s') + sec)) '+%H:%M') && alart "$(($sec / 60))min EXT. TIME"

