#! /bin/sh

dp="$HOME/.config"
gdp="$HOME/mdwm/dotfiles/.config"


cp $dp/sxhkd/sxhkdrc $gdp/sxhkd/sxhkdrc && echo -e "--------------\n sxhkd copied \n--------------"
cp $dp/dunst/dunstrc $gdp/dunst/dunstrc && echo -e " dunstrc copied \n----------------------"
cp $dp/nvim/init.vim $gdp/nvim/init.vim && echo -e " nvim-init.vim copied \n----------------------"
cp $dp/picom/picom.conf $gdp/picom/picom.conf && echo -e " picom.conf copied \n--------------"


