#!/bin/sh


compiler=""

[ -x "$(command -v clang)" ] && compiler="clang"
[ -x "$(command -v gcc)" ] && compiler="gcc"

if [ -x "compiler" ]; then
    echo "No compiler found"
    exit 1
fi

[ "$1" = "" ] && echo "no input file" && exit 1

out="/tmp/a.out_$(date '+%s')"




echo "useing \"$compiler\""
echo
"$compiler" -o "$out" "$1" && "$out"

[ -f "$out" ] && rm "$out"
