#!/bin/sh

name="$2"
path="$PWD/$1"
cpath="$HOME/.cache/class-links"
indx=1
tempLinks="$PWD/bear-links"
finalLinks="$PWD/$name-links"

sed "s/<\//\n/g ; s/\"/\n/g" $path | grep "facebook.com" > $tempLinks


while read line
	do
		echo "$line;$indx-$name.mp4" >> $finalLinks
		echo "$indx-$name"
		indx=$((indx + 1))
	done < $tempLinks

rm $tempLinks
