#!/bin/sh

link="${HOME}/Arabic/Av-nahw"

if [ "$1" = "-d" ]
then
	class="$( ls $link | dmenu -p "Calss :" -l 8 -i )"

else
	[ -z "$1" ] && f="fzf" || f="fzf -q "$*""
	class="$( ls $link | $f )"
fi

[ -n "$class" ] && mpv --speed=2 "$link/$class"

exit
