#!/bin/bash

##Dependencies is only  "fzf"
## it's only for me so don't worry!!!


path="/home/sk/Dream/Av-nahw"
vid_player="mpv -fs --speed=1.75 /home/sk/Dream/Av-nahw/"


[ -z "$*" ] && $vid_player"$( ls $path | fzf )" || $vid_player"$( ls $path | fzf -q "$*" )"

