#! /bin/sh

link="$1"
name=$2
ytc="yt-dlp --cookies-from-browser brave $link"

$ytc  -F

echo -n "Give the res pls: "
read res

[ -z "$name" ] && echo -n "Name of the vid: " && read name

$ytc -f $res -o "$name"

