#!/bin/sh
# distrobox_binary
# name: arch1
if [ ! -f /run/.containerenv ] && [ ! -f /.dockerenv ]; then
	command="/usr/bin/distrobox-enter  -n arch1 --  /usr/bin/Hyprland  "

	for arg in "$@"; do
		if echo "${arg}" | grep -Eq "'|\""; then
			command="${command} \
				$(echo "${arg}" | sed 's|\\|\\\\|g' |
				sed 's| |\\ |g' |
				sed 's|\$|\\\$|g' |
				sed "s|'|\\\'|g" |
				sed 's|"|\\\"|g')"
		elif echo "${arg}" | grep -q "'"; then
			command="${command} \"${arg}\""
		else
			command="${command} '${arg}'"
		fi
	done
	eval ${command}
else
	/usr/bin/Hyprland "$@"
fi
