#! /bin/sh

notify="notify-send -u low  -t 650"
dwmb="pkill -RTMIN+11 dwmblocks"

if [ "$1" = "ar" ]
then
	setxkbmap ar
	$dwmb
	$notify "Arabic" "Is the layout"
	sleep 2
	xmodmap ~/.Xmodmap &
	exit 0
fi


kb="$(setxkbmap -query | grep layout)"

if [ "layout:     us" = "$kb" ]
then
	setxkbmap bd probhat
	$dwmb
	$notify "Bangla Prob" "Is the layout"
	sleep 2
	xmodmap ~/.Xmodmap &

elif [ "layout:     bd" = "$kb" ] || [ "layout:     ar" = "$kb" ]
then
	setxkbmap us
	$dwmb
	$notify "English" "Is the layout"
	sleep 2
	xmodmap ~/.Xmodmap &
fi
