#!/bin/sh
# open pdf form web; donload only once

set -e


dir="/tmp"
# name=$(printf '%s' ${1} | grep -o '[^/]*$')
name=$(printf '%s' ${1} | grep -o '[^/]*$' | python3 -c "import sys; from urllib.parse import unquote; print(unquote(sys.stdin.read()));")
file="$dir/$name"

[ "$1" = "" ] && echo "no link provided" && exit 1

stat "$file" &> /dev/null && zathura "$file" && exit 0

pwd=$(pwd)
cd ${dir}
ok=0
wget ${1} && ok=1
cd ${pwd}

[ $ok = 1 ] && echo && echo "$file" && echo
[ $ok = 1 ] && zathura "$file"


