#!/bin/sh
# open pdf form web; donload only once


dir="/tmp"
file="$dir/$(printf '%s' ${1} | grep -o '[^/]*$')"

[ "$1" = "" ] && echo "no link provided" && exit 1

stat "$file" &> /dev/null && zathura "$file" && exit 0

pwd=$(pwd)
cd ${dir}
ok=0
wget ${1} && ok=1
cd ${pwd}

[ $ok = 1 ] && zathura "$file"


