#!/bin/sh

file="$HOME/Documents/quotes/quotes"
cache="$HOME/.cache/.last_quote"

q=$(shuf "$file" | head -1)

## loop until it's a new quote
while [ "$q" = "$(cat ${cache} )" ]
do
    q=$(shuf "$file" | head -1)
done

echo "$q" > ${cache}

[ "$1" = "f" ] && printf "\n  %s \n" "$q" && exit 0

echo "$q"
