#! /bin/sh

path="$HOME/.cache/stime"
js="$path/js"
tmt="$path/tmt"
tm="$path/tm"
[ ! -e "$path" ] && mkdir $path && echo -e " New file created \n"


curl -s "https://api.aladhan.com/v1/calendarByCity?city=tangail&country=bangladesh&method=1"> $js

## If there is no net then show the archived vertion "cached version"
tim=$( head -1 $js )
if [ -z "$tim" ]
then	
	echo -e "\n       Showing the \033[1;31mOFFLINE\033[0m version\n\t─────────────────────────" 
	awk '{ printf"\t   %s \033[1;35m%s  \033[1;31m%s\033[0m %s\n\t─────────────────────────\n", $1, $2, $3, $4, $5 }' $tm
	echo

	exit 0
fi


## if internet is avialavle then process and show and save the time
jq "." $js |
	grep -m 7 "Fajr\|Sunrise\|Dhuhr\|Asr\|Sunset\|Maghrib\|Isha" | 
	sed "s/\"//g ; s/(+06),//g ; s/\s*// ; s/:/ -/
	s/Fajr/🌇 Fajr/
	s/Sunrise/🌅 Sunrise/
	s/Dhuhr/☀️  Dhuhr/
	s/Asr/🌳 Asr/
	s/Sunset/🌇 Sunset/
	s/Maghrib/🌥️ Mahgrib/
	s/Isha/🌃 Isha/" > $tmt

[ -e $tm ] && rm -rf $tm
while read line
	do
		name=$(echo $line | cut -d "-" -f 1)
		bdTime=$( date "+%I:%M %p" --date="$( echo $line | cut -d "-" -f 2 )" )
		echo $name $bdTime >> $tm
	done < $tmt


echo -e "\n       Showing the \033[1;31mONLINE\033[0m version\n\t─────────────────────────" 
awk '{ printf"\t   %s \033[1;35m%s  \033[1;31m%s\033[0m %s\n\t─────────────────────────\n", $1, $2, $3, $4, $5 }' $tm
echo
