#! /bin/sh

# colors
colR='\033[0m'		#color reset
yollow='\033[1;33m'


path="$HOME/.cache/stime"
location="$path/location"
js="$path/js"
tmt="$path/tmt"
tm="$path/tm"
dwmb="pkill -RTMIN+13 dwmblocks"

[ ! -e "$path" ] && mkdir $path && echo -e " New file created \n"

if [ ! -e "$location" ] || [ "$1" == "-c" ]
	then
		[ ! -e "$location" ] && echo "AssalamuAlaikum friend. \nNo locatin imfo found This is the first time you are running this script \nPls give the name of your city and country \nbtw it's stored locally no worris" 

		echo -n "Whats the name of your city? : " && read city
		echo -n "Whats the name of your country? : " && read country
		
		echo -e "${yollow}[Tip]:${colR} if the script doesnt work then you should cat \"$locatin\" path and cheak the names"
		echo -e "if its wrong you can edit the file or use ${yollow}salah -c${colR} to change it"

		echo "$city;$country" | tr '[:upper:]' '[:lower:]' > $location
		
fi
		

curl -s "https://api.aladhan.com/v1/calendarByCity?city=$(cat $location | cut -d ";" -f 2)&country=$(cat $location | cut -d ";" -f 2)&method=1"> $js

## If there is no net then show the archived vertion "cached version"
tim=$( head -1 $js )
if [ -z "$tim" ]
then	
	echo -e "\n       Showing the \033[1;31mOFFLINE\033[0m version\n\t─────────────────────────" 
	awk '{ printf"\t   %s \033[1;35m%s  \033[1;31m%s\033[0m %s\n\t─────────────────────────\n", $1, $2, $3, $4, $5 }' $tm
	echo

	exit 0
fi


## if internet is avialavle then process and show and save the time
jq "." $js |
	grep -m 7 "Fajr\|Sunrise\|Dhuhr\|Asr\|Sunset\|Maghrib\|Isha" | 
	sed "s/\"//g ; s/(+06),//g ; s/\s*// ; s/:/ -/
	s/Fajr/🌇 Fajr/
	s/Sunrise/🌅 Sunrise/
	s/Dhuhr/☀️  Dhuhr/
	s/Asr/🌳 Asr/
	s/Sunset/🌇 Sunset/
	s/Maghrib/🌥️ Mahgrib/
	s/Isha/🌃 Isha/" > $tmt

[ -e $tm ] && rm -rf $tm
while read line
	do
		name=$(echo $line | cut -d "-" -f 1)
		bdTime=$( date "+%I:%M %p" --date="$( echo $line | cut -d "-" -f 2 )" )
		echo $name $bdTime >> $tm
	done < $tmt


echo -e "\n       Showing the \033[1;31mONLINE\033[0m version\n\t─────────────────────────" 
awk '{ printf"\t   %s \033[1;35m%s  \033[1;31m%s\033[0m %s\n\t─────────────────────────\n", $1, $2, $3, $4, $5 }' $tm
echo
$dwmb
