#!/bin/bash
path="$HOME/.cache/stime"
mkdir -p "$path"

path="$path/RamadanTime.txt"

link="https://hamariweb.com/islam/tangail_ramadan-timing13785.aspx"

curl -s "$link" | grep '<td' | head -3 | sed 's/<td>//g; s/<\/td>//g; s/<span>//g; s/<\/span>//g' > "$path"

while read l
do
	time=$(echo $l | cut -d " " -f 2)
	case $time in
		am)
			printf "Sehri: %s\n" "$l"
			;;
		pm)
			printf "Iftar: %s\n" "$l"
			;;
		*)
			printf "%s\n" "$l"
	esac

done < "$path"
