#! /bin/sh

#colors
cOff='\033[0m'
bRed='\033[1;31m'


link="$1"
[ -z "$link" ] && echo -en "give a yt or fb ${bRed}link${cOff}: " && read link
[ -z "$link" ] && echo -e "No link provided ${bRed}self-destructing${cOff}" && exit 1

name=$2


if [[ ${link} =~ https://(www\.)?youtu.* ]]
then
	echo -e "${bRed}YT link${cOff}"
	ytl="yt-dlp $link"
else
	echo -e "${bRed}fb link I guess${cOff}"
	ytl="yt-dlp --cookies-from-browser brave $link"
fi


$ytl  -F

echo -ne "Give the ${bRed}resulution${cOff}: " && read res
[ -z $res ] && echo -e "going back to ${bRed}default Resutlation${cOff}" || f_res="-f $res"

[ -z $name ] && echo -en "${bRed}Name${cOff} of the vid: " && read name
[ -z $name ] && echo -e "going back to ${bRed}default Name${cOff}" || o_name="-o \"$name\"" 

$ytl $f_res $o_name

