#! /bin/sh

#dependencies
# 1. ytfzf
# 2. mpv

link="$(ytfzf -I L $* )"

echo "-------------------------------------------"
echo " \"$*\"  is loading w8"
echo "  Hope yout are wathcing something good 😅"
echo "-------------------------------------------"


mpv -fs $link

