#! /bin/sh


path="$HOME/.cache/stime"
js="$path/js"
timee="$path/tmtDb"
time="$path/tmDb"
location="$path/location"
city="$(cat $location | cut -d ";" -f 1)" 
country="$(cat $location | cut -d ";" -f 2)"
[ -z "$city" ] && city="dhaka"
[ -z "$country" ] && country="bangladesh"
curl -s "https://api.aladhan.com/v1/calendarByCity?city=${city}&country=${country}&method=1"> $js

## If there is no net then show the archived vertion "cached version"
tim=$( head -1 $js )
if [ -z "$tim" ]
then

	[ $(date +"%H" | sed "s/00/1/") -ge 1 ] && [ $(date +"%H") -le 6 ] && sed -n 1p $time && exit 0
	[ $(date +"%H") -ge 7 ] && [ $(date +"%H") -le 13 ] && sed -n 2p $time && exit 0
	[ $(date +"%H") -ge 14 ] && [ $(date +"%H") -le 17 ] && sed -n 3p $time&& exit 0
	[ $(date +"%H") -ge 18 ] && [ $(date +"%H") -le 18 ] && sed -n 4p $time && exit 0
	[ $(date +"%H") -ge 19 ] && [ $(date +"%H") -le 24 ] && sed -n 5p $time && exit 0

	exit 0
fi


jq "." $js|
        grep -m 5 "Fajr\|Dhuhr\|Asr\|Maghrib\|Isha" |
        sed "s/\"//g ; s/(+06),//g ; s/\s*// ; s/:/ -/ " > $timee

# .....
rm -rf $time

while read line
	do
		name=$(echo $line | cut -d "-" -f 1)
		bdTime=$( date "+%I:%M" --date="$( echo $line | cut -d "-" -f 2 )" )
		echo $name $bdTime >> $time
	done < $timee

pkill -RTMIN+13 dwmblocks
[ $(date +"%H" | sed "s/00/1/") -ge 1 ] && [ $(date +"%H") -le 6 ] && sed -n 1p $time && exit 0
[ $(date +"%H") -ge 7 ] && [ $(date +"%H") -le 13 ] && sed -n 2p $time && exit 0
[ $(date +"%H") -ge 14 ] && [ $(date +"%H") -le 17 ] && sed -n 3p $time&& exit 0
[ $(date +"%H") -ge 18 ] && [ $(date +"%H") -le 18 ] && sed -n 4p $time && exit 0
[ $(date +"%H") -ge 19 ] && [ $(date +"%H") -le 24 ] && sed -n 5p $time && exit 0
