#!/bin/sh

# this script only works with the site teacchingbd24 site to download questions and idk for now

path="$HOME/.cache/prosno-site"
html="$path/html"
[ -e "$path" ] && rm -rf $path
mkdir -p $path

# [ -z "$1" ] && printf "link of the tcc site: " && read link || link=$1
[[ ! ${1} =~ https://teachingbd24.com/.* ]] && printf "link of the tcc site: " && read link || link=$1

#last time cheaking 
[[ ! ${link} =~ https://teachingbd24.com/.* ]] && echo -e "\n  U dummy give a link of the \"https://teachingbd24.com/\" site \n" && exit 1

curl -s "$link" | grep -o "https://teachingbd24.com/.*board/" > $html

content=$(cat $html)

[ -z $content ] && echo -e "\n The sight could not be scraped \n" && exit 1


while read link
	do
		wget $(curl -s "$link" | grep -o "<a href=\".*.pdf" | cut -d"\"" -f2)

	done < $html
