#!/bin/sh

[ -e $HOME/.cache/mT ] && rm -rf $HOME/.cache/mT 

mkdir -p $HOME/.cache/mT

[ -z "$*" ] && printf | dmenu -p "Name Pls: " && read query || query="$*"



queryM=$(echo $query | sed "s/[[:space:]]/+/g")

#vars
link="https://1337x.to"
names="$HOME/.cache/mT/t-imfo.txt"
serch="https://1337x.to/search/"$queryM"/1/"
site="$HOME/.cache/mT/mSite.txt"


#######################
#Get name of the movie#
#######################
curl -s $serch | grep -o '<a href="/torrent/.*</a>' | cut -d '"' -f 2 > $names
cat $name
sTorr=$(cat $names |cut -d "/" -f 4 | sed "s/-/ /g" | dmenu) && exit
sTorr=$(cat $names |cut -d "/" -f 4 | sed "s/-/ /g" | dmenu -l 7 | sed "s/[[:space:]]/-/g")
sTorrId=$(grep $sTorr $names)
curl -s $link$sTorrId > $site

magnet=$(cat $site | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)

qbittorrent $magnet
# echo $magnet | dmenu -l 1

exit 0
